'use client'

import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function HowItStartedPage() {
  return (
    <main className="min-h-screen bg-white font-sans">
      <Navbar />

      {/* Hero */}
      <section className="relative h-72 flex items-end overflow-hidden">
        <img
          src="https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=1600&q=80"
          alt="Vermont winter farm"
          className="absolute inset-0 w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/30 to-transparent" />
        <div className="relative z-10 max-w-6xl mx-auto px-6 pb-12 w-full">
          <p className="uppercase tracking-widest text-xs font-semibold mb-2" style={{ color: '#00B4D8' }}>The Origin</p>
          <h1 className="text-4xl md:text-5xl font-extrabold text-white tracking-tight">How It Started</h1>
        </div>
      </section>

      {/* Article content */}
      <article className="py-16 px-6">
        <div className="max-w-3xl mx-auto">

          <p className="text-xl text-gray-600 leading-relaxed mb-8 font-medium">
            It started with a bad recommendation. Someone told a first-time visitor to Killington to try a restaurant that had been closed for two years. That single moment of frustration eventually became Killington Getaway.
          </p>

          <div className="flex flex-col gap-6 text-gray-600 text-sm leading-relaxed">

            <h2 className="text-xl font-extrabold text-gray-900 mt-4">The Problem with Ski Town Guides</h2>
            <p>
              If you've ever searched for "best restaurants in Killington" or "where to stay near Killington ski resort," you've seen the problem. The results are full of articles written by people who visited once in 2018, listicles generated by algorithms that have never been within 200 miles of Vermont, and review aggregators that mix legitimate businesses with listings that are years out of date.
            </p>
            <p>
              Ski towns have a particular problem with this. The turnover is high, seasons are compressed, and the people who actually know the mountain — the instructors, the patrol, the lift operators, the bartenders at the Wobbly Barn who've been there for twenty years — aren't usually the ones writing guides.
            </p>

            <h2 className="text-xl font-extrabold text-gray-900 mt-4">A Local's Frustration</h2>
            <p>
              Jonas, one of the co-founders of Killington Getaway, had been skiing Killington for over a decade when he started getting texts from friends visiting for ski weekends. "Where should we stay?" "Where do locals eat?" "Is the Wobbly Barn actually worth it or is it just for tourists?"
            </p>
            <p>
              He'd answer the same questions over and over. He knew which condo complexes were ski-in/ski-out and which ones weren't. He knew which restaurants had the best happy hour deals. He knew that the best mountain lunch was a sandwich from the Killington Deli, not the overpriced slope-side options.
            </p>
            <p>
              The problem was that knowledge lived entirely in his phone's text history. There was no place online where a first-time visitor could get the same quality of information that a local friend could provide.
            </p>

            <h2 className="text-xl font-extrabold text-gray-900 mt-4">Building the Guide</h2>
            <p>
              The first version of Killington Getaway was launched with a simple premise: every listing had to be verified by someone who had actually been there recently. No SEO-farm content. No paid placements. No listings pulled from a national database without a local review.
            </p>
            <p>
              The team grew organically. Other Killington locals — Marc, Jorge, Paul, John — joined to cover the areas they knew best. The summer guide was written by people who hiked the trails every July. The apres guide was written by people who close the Pickle Barrel on Saturdays.
            </p>
            <p>
              That authenticity is still the core of what Killington Getaway is. The platform has gotten bigger, the design has gotten cleaner, and the listings database now covers hundreds of businesses in the region — but the standard hasn't changed. If we don't know it's good, it doesn't go on the list.
            </p>

            <h2 className="text-xl font-extrabold text-gray-900 mt-4">Where We Are Today</h2>
            <p>
              Killington Getaway is now the most comprehensive independent guide to the Killington region. We cover lodging, dining, activities, gear shops, mountain conditions, events, and everything in between. We're a Certified B Corporation, which means we've passed an independent audit confirming that our business structure and practices meet high standards for social and environmental impact.
            </p>
            <p>
              A percentage of our affiliate revenue goes directly to YES (Youth Enrichment Services) and other Vermont nonprofits that support access to outdoor education and winter sports for kids who wouldn't otherwise be able to participate.
            </p>
            <p>
              The goal has always been the same: make it easier for people to have the best possible time in one of the most special places in New England. Killington is an extraordinary place. It deserves an extraordinary guide.
            </p>

          </div>

          {/* Pull quote */}
          <blockquote className="my-10 border-l-4 pl-6 py-2" style={{ borderColor: '#00B4D8' }}>
            <p className="text-xl font-semibold text-gray-800 leading-relaxed italic">
              "We answer the question: what would a local tell you if you texted them right now?"
            </p>
            <cite className="text-sm text-gray-400 mt-2 block not-italic">— Killington Getaway, founding principle</cite>
          </blockquote>

        </div>
      </article>

      {/* CTA */}
      <section className="bg-gray-50 border-t border-gray-100 py-14 px-6 text-center">
        <div className="max-w-2xl mx-auto">
          <h2 className="text-2xl font-extrabold text-gray-900 mb-3">Read More About Us</h2>
          <div className="flex gap-4 justify-center flex-wrap mt-6">
            <Link href="/our-story" className="inline-block text-white font-bold px-8 py-3 rounded-full hover:opacity-90 transition-opacity" style={{ backgroundColor: '#00B4D8' }}>
              Our Story
            </Link>
            <Link href="/our-team" className="inline-block font-bold px-8 py-3 rounded-full border-2 hover:opacity-70 transition-opacity" style={{ color: '#00B4D8', borderColor: '#00B4D8' }}>
              Meet the Team
            </Link>
            <Link href="/giving-back" className="inline-block font-bold px-8 py-3 rounded-full border-2 hover:opacity-70 transition-opacity" style={{ color: '#00B4D8', borderColor: '#00B4D8' }}>
              Giving Back
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}
