'use client'

import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Hero from '../components/Hero'

export default function HowItStartedPage() {
  return (
    <main className="min-h-screen bg-white font-body">
      <Navbar />

      <Hero title="How It Started" subtitle="The Origin Story" image="https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=1600&q=80" />

      {/* Article content */}
      <article className="py-24 px-6 bg-white">
        <div className="max-w-4xl mx-auto">
          <p className="text-2xl md:text-3xl font-heading font-black text-brand-navy leading-relaxed mb-16 tracking-tight">
            It started with a bad recommendation. Someone told a first-time visitor to Killington to try a restaurant that had been closed for two years. That single moment of frustration eventually became Killington Getaway.
          </p>

          <div className="flex flex-col gap-12 text-gray-400 text-lg font-medium leading-relaxed">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-start">
              <div className="flex flex-col gap-6">
                <h2 className="text-2xl font-heading font-black text-brand-navy uppercase tracking-tight">The Problem with <span className="text-brand-green">Guides</span></h2>
                <p>
                  If you&apos;ve ever searched for &quot;best restaurants in Killington&quot; or &quot;where to stay near Killington ski resort,&quot; you&apos;ve seen the problem. The results are full of articles written by people who visited once in 2018, listicles generated by algorithms, and reviews that are years out of date.
                </p>
              </div>
              <div className="flex flex-col gap-6">
                <p>
                  Ski towns have a particular problem with this. The turnover is high, seasons are compressed, and the people who actually know the mountain — the instructors, the patrol, the lift operators — aren&apos;t usually the ones writing guides.
                </p>
              </div>
            </div>

            <div className="h-[1px] bg-gray-100 my-8" />

            <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-start">
              <div className="flex flex-col gap-6">
                <h2 className="text-2xl font-heading font-black text-brand-navy uppercase tracking-tight">A Local&apos;s <span className="text-brand-green">Frustration</span></h2>
                <p>
                  Jonas, one of the co-founders of Killington Getaway, had been skiing Killington for over a decade when he started getting texts from friends visiting for ski weekends. &quot;Where should we stay?&quot; &quot;Where do locals eat?&quot;
                </p>
              </div>
              <div className="flex flex-col gap-6">
                <p>
                  He knew which condo complexes were ski-in/ski-out and which ones weren&apos;t. He knew which restaurants had the best happy hour deals. He knew that the best mountain lunch was a sandwich from the Killington Deli, not the overpriced slope-side options.
                </p>
              </div>
            </div>

            {/* Pull quote */}
            <blockquote className="my-16 relative p-12 bg-gray-50 rounded-[3rem] border border-gray-100 overflow-hidden">
              <div className="absolute top-0 left-0 w-2 h-full bg-brand-green" />
              <div className="relative z-10">
                <p className="text-2xl md:text-3xl font-heading font-black text-brand-navy leading-tight mb-6 italic">
                  &quot;We answer the question: what would a local tell you if you texted them right now?&quot;
                </p>
                <cite className="text-[10px] font-black text-gray-300 uppercase tracking-widest not-italic flex items-center gap-3">
                  <span className="w-8 h-[1px] bg-gray-200" />
                  Killington Getaway, Founding Principle
                </cite>
              </div>
            </blockquote>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-start">
              <div className="flex flex-col gap-6">
                <h2 className="text-2xl font-heading font-black text-brand-navy uppercase tracking-tight">Building the <span className="text-brand-green">Guide</span></h2>
                <p>
                  The first version of Killington Getaway was launched with a simple premise: every listing had to be verified by someone who had actually been there recently. No SEO-farm content. No paid placements.
                </p>
              </div>
              <div className="flex flex-col gap-6">
                <p>
                  The team grew organically. Other Killington locals — Marc, Jorge, Paul, John — joined to cover the areas they knew best. The summer guide was written by people who hiked the trails every July. The apres guide was written by people who close the Pickle Barrel on Saturdays.
                </p>
              </div>
            </div>

            <div className="h-[1px] bg-gray-100 my-8" />

            <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-start">
              <div className="flex flex-col gap-6">
                <h2 className="text-2xl font-heading font-black text-brand-navy uppercase tracking-tight">Where We Are <span className="text-brand-green">Today</span></h2>
                <p>
                  Killington Getaway is now the most comprehensive independent guide to the Killington region. We cover lodging, dining, activities, gear shops, mountain conditions, and everything in between.
                </p>
              </div>
              <div className="flex flex-col gap-6">
                <p>
                  We&apos;re a Certified B Corporation, which means we&apos;ve passed an independent audit confirming our commitment to social and environmental impact. A percentage of our revenue goes directly to YES (Youth Enrichment Services).
                </p>
              </div>
            </div>
          </div>
        </div>
      </article>

      {/* CTA Section */}
      <section className="py-24 px-6 text-center bg-gray-50/50 border-t border-gray-100">
        <div className="max-w-4xl mx-auto bg-brand-navy rounded-[4rem] py-16 px-10 border border-brand-navy shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-brand-green/10 rounded-full -mr-32 -mt-32" />
          <h2 className="text-4xl md:text-5xl font-heading font-black text-white mb-4 tracking-tight uppercase relative z-10">Read More <span className="text-brand-green">About Us</span></h2>
          <div className="flex gap-6 justify-center flex-wrap relative z-10 mt-12">
            <Link href="/our-story" className="bg-brand-green text-white font-black px-12 py-5 rounded-full hover:bg-brand-green/90 transition-all shadow-xl uppercase tracking-widest text-sm">
              Our Story
            </Link>
            <Link href="/our-team" className="bg-white text-brand-navy font-black px-12 py-5 rounded-full hover:bg-gray-100 transition-all shadow-xl uppercase tracking-widest text-sm">
              Meet the Team
            </Link>
            <Link href="/giving-back" className="bg-transparent text-white border-2 border-white/20 font-black px-12 py-5 rounded-full hover:bg-white/5 transition-all uppercase tracking-widest text-sm">
              Giving Back
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}
